# Generated by Django 4.1.7 on 2023-05-30 06:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Each ticket has a title wich is book title and author.",
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Each note needs a description, it must describe the book.",
                        max_length=2048,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Each ticket can have an image, but he can be blank.",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="ticket creation date is automatically filled in.",
                    ),
                ),
                (
                    "has_review",
                    models.BooleanField(
                        default=False,
                        help_text="True, if at least one review exists for this ticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Each ticket has been created by one user.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Each review has rating wich is an integer number between 0 an",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        help_text="The headline can't be blank. Headline max length 128.",
                        max_length=128,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="The body can be blank. Body max length is 8192.",
                        max_length=8192,
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="Each review is related to Ticket describing a book or an",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.ticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
