# Generated by Django 4.1.7 on 2023-05-09 10:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(
                blank=True,
                help_text="The body can be blank. Body max length is 8192.",
                max_length=8192,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="headline",
            field=models.CharField(
                help_text="The headline can't be blank. Headline max length 128.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                help_text="Each review has rating wich is an integer number between 0 an",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.ForeignKey(
                help_text="Each review is related to Ticket describing a book or an",
                on_delete=django.db.models.deletion.CASCADE,
                to="reviews.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Each note needs a description, it must describe the book.",
                max_length=2048,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="has_review",
            field=models.BooleanField(
                default=False,
                help_text="True, if at least one review exists for this ticket",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Each ticket can have an image, but he can be blank.",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="ticket creation date is automatically filled in.",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(
                help_text="Each ticket has a title wich is book title and author.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                help_text="Each ticket has been created by one user.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
