# Generated by Django 4.1.7 on 2023-04-07 06:36
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


# def create_groups(apps, schema_migration):
#     emit_post_migrate_signal(verbosity=1, interactive=False, db='default')

#     User = apps.get_model('authentication', 'User')
#     UserFollows = apps.get_model('authentication', 'UserFollows')
#     Group = apps.get_model('auth', 'Group')
#     Permission = apps.get_model('auth', 'Permission')

#     add_ticket = Permission.objects.get(codename='add_ticket')
#     change_ticket = Permission.objects.get(codename='change_ticket')
#     delete_ticket = Permission.objects.get(codename='delete_ticket')
#     view_ticket = Permission.objects.get(codename='view_ticket')

#     creator_permissions = [
#         add_ticket,
#         change_ticket,
#         delete_ticket,
#         view_ticket,
#     ]

#     creators = Group(user.id)
#     creators.save()
#     creators.permissions.set(creator_permissions)

#     subscribers = Group(UserFollows.id)
#     subscribers.save()
#     subscribers.permissions.add(view_ticket)

#     for user in User.objects.all():
#         if user == creators:
#             creators.user_set.add(user)
#         if user == subscribers:
#             subscribers.user_set.add(user)


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    # operations = [migrations.RunPython(create_groups)]
